name: Continuous Integration for Pull Requests

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  client:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        working-directory: ./client
        run: npm install
      - name: Run Formatter
        working-directory: ./client
        run: npm run format
      - name: Fix Lint Issues
        working-directory: ./client
        run: npm run lint:fix
        continue-on-error: true
      - name: Run Linter
        working-directory: ./client
        run: npm run lint
      
